#!/usr/bin/env python3
"""Publish the auto-configuration bands from the module that uses them.

The Tesseract band edges were written out by hand in five places -- two
docstrings, `CLAUDE.md`, and two site pages -- with nothing checking any of
them against the code. That was survivable while the numbers were hand-fitted
and never moved. They are fitted from a measured sweep now, and they move, so
the published copies have to be generated or they become wrong quietly.

This writes `site/data/tuning.toml` from `tetrak_ocr.backends.tuning`, which
Hugo reads at build time through `partials/bands.html`. Same principle as the
benchmark tables: the figure is read from its source at render time and never
transcribed into prose.

Prerequisites:
    The package importable -- `pip install -e .`. `tuning` is standard library
    only, so no OCR stack is needed.

Run:
    python tools/generate_tuning_data.py

    Also runs before Hugo via `npm run build`, alongside the API reference and
    the Mermaid diagrams.
"""

from __future__ import annotations

import math
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "site" / "data" / "tuning.toml"

sys.path.insert(0, str(REPO_ROOT / "src"))


def _quote(value: str) -> str:
    """TOML basic string. The provenance text carries quotes and backslashes."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def render(rows: list[dict[str, object]], provenance: dict[str, str]) -> str:
    """Return the TOML Hugo reads.

    Hand-rolled rather than via a writer library: this is the only TOML the
    build generates, the shape is four scalar fields, and `tomli-w` would be a
    dependency for it. `tomllib` parses the result back in `main()`, so a
    quoting mistake fails here rather than in Hugo.
    """
    lines = [
        "# Generated by tools/generate_tuning_data.py. Do not edit.",
        "#",
        "# The Tesseract auto-configuration bands, read from",
        "# tetrak_ocr.backends.tuning so the published values cannot drift from",
        "# the ones the code uses. The bands themselves are fitted -- see",
        "# evaluation/ocr/calibration/fit.py.",
        "",
    ]
    for row in rows:
        upper = row["upper"]
        lines += [
            "[[band]]",
            f"feature = {_quote(str(row['feature']))}",
            f"setting = {_quote(str(row['setting']))}",
            f"lower = {float(row['lower'])!r}",
            # `inf` is valid TOML and Hugo reads it, but a page that prints it
            # reads badly. The template tests `unbounded` instead.
            f"unbounded = {'true' if math.isinf(float(upper)) else 'false'}",
            *([] if math.isinf(float(upper)) else [f"upper = {float(upper)!r}"]),
            f"range = {_quote(str(row['range']))}",
            f"value = {float(row['value'])!r}",
            # str(), not %g: a contrast of 1.0 is a multiplier and reads
            # wrong as "1", while a psm of 12 must not gain a decimal point.
            # describe() already carries the right type for each family.
            f"display = {_quote(str(row['value']))}",
            "",
        ]

    lines.append("[provenance]")
    lines += [f"{key} = {_quote(value)}" for key, value in provenance.items()]
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    try:
        from tetrak_ocr.backends import tuning
    except ImportError as exc:  # pragma: no cover -- a setup problem, not a code path
        print(
            f"generate_tuning_data: cannot import tetrak_ocr.backends.tuning ({exc}).\n"
            "  Install the package first:  pip install -e .",
            file=sys.stderr,
        )
        return 1

    text = render(tuning.describe(), tuning.FIT_PROVENANCE)

    # Parse it back before writing. A page silently missing its band table
    # because of an unescaped quote is exactly the failure this file exists to
    # prevent, and Hugo reports a bad data file as an empty one.
    parsed = tomllib.loads(text)
    expected = len(tuning.CONTRAST_BANDS) + len(tuning.PSM_BANDS)
    if len(parsed.get("band", [])) != expected:
        print(
            f"generate_tuning_data: rendered {len(parsed.get('band', []))} bands, "
            f"expected {expected}",
            file=sys.stderr,
        )
        return 1

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT)} with {expected} bands")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
